const PRODUCT_INFO = {
  name: "FIAS App",
  description: "Generated by create next app",
  logo: "https://shadcnblocks.com/images/block/logos/shadcnblockscom-icon.svg",
  url: "https://www.shadcnblocks.com",
  socials: {
    telegram: "https://t.me/usmanov_dev",
    instagram: "https://t.me/usmanov_dev",
    youtube: "https://t.me/usmanov_dev",
    linkedin: "https://www.linkedin.com/in/usmonov-azizbek/",
  },
  contact: {
    phone: "+998901234567",
    email: "contact@fias.uz"
  },
  terms_of_use: "",
  creator: "FIAS App"
}

export {PRODUCT_INFO}